version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    container_name: pending-notification-postgres
    environment:
      POSTGRES_DB: pending_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: pending-notification-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  redis:
    image: redis:7-alpine
    container_name: pending-notification-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:

